name: Build
on: [pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install gd
        run: sudo apt install libgd-dev
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
