name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.ssh_key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Install soft dependencies
      - name: Install gd
        run: sudo apt install libgd-dev
      # Install paakges dependencies
      - run: npm ci
      # Build
      - run: npm run build
      # Deploy
      - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress . vlad805@135.181.147.70:/home/vlad805/projects/sights-backend/
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -t vlad805@135.181.147.70 -c "cd /home/vlad805/projects/sights-backend/ && npm ci && pm2 restart sights-backend"