name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.ssh_key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Install dependencies
      - run: npm ci
      # Build
      - run: npm run build
      # Deploy
      - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress . vlad805@${{ secrets.ssh_host }}:/home/vlad805/projects/@sights/backend/
      # Restart server
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_host }}
          username: vlad805
          key: ${{ secrets.ssh_key }}
          script_stop: true
          script: |
            export PATH=$PATH:/usr/bin/:/home/vlad805/.nvm/versions/node/v12.19.0/bin/
            cd /home/vlad805/projects/@sights/backend/
            npm ci
            pm2 restart sights-backend -s
            exit
