name: Unit test
on: [push]
jobs:
  eslint:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: npm t
