name: Unit test
on: [push, pull_request]
jobs:
  eslint:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install gd
        run: sudo apt install libgd-dev
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: npm t
